services:
  - type: web
    name: portfolio-chatbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT chatbot_api:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
    healthCheckPath: /
    autoDeploy: true